
services:
  db:
    # MacのApple Silicon(M1/M2)環境などの場合は下記のplatform指定が必要
    platform: linux/amd64
    image: mysql:5.7
    container_name: db
    # MySQLデータ永続化用
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_fB3uWvTS
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass_Ck6uTvrQ

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    # WordPressファイル・PHP設定ファイルをマウント
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user_pass_Ck6uTvrQ

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      # 下記はなくても動きますが指定可能
      # PMA_ARBITRARY: 1
      # PMA_HOST: db
      # PMA_USER: user
      # PMA_PASSWORD: user_pass_Ck6uTvrQ
      # 上記のような環境変数の設定方法もあります
      MYSQL_ROOT_PASSWORD: root_pass_fB3uWvTS
