version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: db
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_fB3uWvTS
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass_Ck6uTvrQ
    command: --max_allowed_packet=256M --innodb_log_file_size=256M --wait_timeout=600 --net_read_timeout=600 --net_write_timeout=600
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    platform: linux/amd64
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user_pass_Ck6uTvrQ
    build:
      context: "./"
      dockerfile: "Dockerfile"
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_fB3uWvTS
      MEMORY_LIMIT: 1024M
      UPLOAD_LIMIT: 128M
      MAX_EXECUTION_TIME: 1800
    networks:
      - app-net

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5001:5001"
    volumes:
      - ./flask_app:/app  # ホストとコンテナを同期
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
